language:
  node_js
node_js:
  - 8
  - 6
install:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g codecov
  - npm install
script:
  - npm run build
  - npm run cover
  - codecov
